sonar.projectKey=dbetancorfp_PYTO_CUADERNO_DE_AULA_V0
sonar.organization=dbetancorfp

sonar.sources=src/backend/src,src/frontend/src
sonar.tests=src/backend/tests,src/frontend/tests
sonar.exclusions=**/dist/**,**/node_modules/**,docs/**,site/**,coverage/**,**/*.md,src/frontend/cypress/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
